/**
 * InternalToolProvider: the extension itself acting as a tool provider.
 *
 * Built-in tools do not depend on an external MCP server; they are implemented locally by the extension
 * (e.g. compact_context triggers context compaction). They are merged with external MCP tools,
 * injected into the web AI prompt, and intercepted at mcpClient.callTool / useMcpCommunication
 *
 * (no MCP connection required).
 * To add a built-in tool: append a definition to the INTERNAL_TOOLS array; dispatch matches by name.
 */
import { createLogger } from '@extension/shared/lib/logger';
import { compactionService } from '../services/compaction.service';
import type { Tool } from '../types/stores';

const logger = createLogger('InternalToolProvider');

export interface InternalToolHandlerArgs {
  [key: string]: unknown;
}

export interface InternalToolDefinition {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
  handler: (args: InternalToolHandlerArgs) => Promise<string>;
}

/** compact_context: trigger a context compaction; the summary is injected into a new conversation. */
const COMPACT_CONTEXT_DEF: InternalToolDefinition = {
  name: 'compact_context',
  description:
    'Compress the current conversation into a structured summary injected into a new chat, for continuing long conversations. The summary is generated by the current conversation AI; the original transcript stays queryable after compaction.',
  inputSchema: {
    type: 'object',
    properties: {
      targetTokens: {
        type: 'number',
        description: 'Target token budget for the summary; default 1200, range 800~3000',
        minimum: 800,
        maximum: 3000,
      },
      todoContext: {
        type: 'string',
        description: 'Summary of pending task state to carry over; ignored if omitted',
      },
    },
    required: [],
  },
  handler: async (args) => {
    const targetTokens = typeof args.targetTokens === 'number' ? args.targetTokens : undefined;
    const todoContext = typeof args.todoContext === 'string' ? args.todoContext : undefined;

    const result = await compactionService.compact({ targetTokens, todoContext });

    if (result.success) {
      return [
        `Context compaction complete. compactionId: ${result.compactionId}, summary ~${result.summaryTokens ?? 0} tokens, continuation message injected into the new conversation.`,
        result.error ? `Note: ${result.error}` : '',
      ]
        .filter(Boolean)
        .join('\n');
    }
    return `Context compaction failed: ${result.error || 'unknown error'}`;
  },
};

const INTERNAL_TOOLS: InternalToolDefinition[] = [COMPACT_CONTEXT_DEF];

/** Whether the given name is a built-in tool name */
export function isInternalTool(name: string): boolean {
  return INTERNAL_TOOLS.some(tool => tool.name === name);
}

/** Built-in tool list (same Tool shape as external MCP tools; schema is a JSON string). */
export function getInternalTools(): Tool[] {
  return INTERNAL_TOOLS.map(tool => ({
    name: tool.name,
    description: tool.description,
    input_schema: tool.inputSchema,
    schema: JSON.stringify(tool.inputSchema),
    internal: true,
  }));
}

/**
 * Execute a built-in tool. Throws for non-built-in names.
 */
export async function executeInternalTool(name: string, args: Record<string, unknown> = {}): Promise<string> {
  const def = INTERNAL_TOOLS.find(tool => tool.name === name);
  if (!def) {
    throw new Error(`Internal tool '${name}' not found`);
  }
  logger.debug(`Executing internal tool: ${name}`, args);
  return def.handler(args);
}
